// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SessionManager.Infrastructure.Data;

#nullable disable

namespace SessionManager.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328224306_AddAgentWindowsMvp")]
    partial class AddAgentWindowsMvp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("SessionManager.Domain.Entities.AgentCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssignedAgentId")
                        .HasMaxLength(120);

                    b.Property<string>("CommandText")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<DateTime?>("CompletedAtUtc");

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000);

                    b.Property<DateTime?>("PickedAtUtc");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<string>("ResultOutput")
                        .HasMaxLength(4000);

                    b.Property<Guid>("ServerId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime?>("UpdatedAtUtc");

                    b.HasKey("Id");

                    b.HasIndex("ServerId", "Status", "CreatedAtUtc");

                    b.ToTable("AgentCommands");
                });

            modelBuilder.Entity("SessionManager.Domain.Entities.AllowedProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<bool>("IsActive");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<DateTime?>("UpdatedAtUtc");

                    b.HasKey("Id");

                    b.HasIndex("ProcessName")
                        .IsUnique();

                    b.ToTable("AllowedProcesses");
                });

            modelBuilder.Entity("SessionManager.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("ClientIpAddress")
                        .HasMaxLength(80);

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000);

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(2000);

                    b.Property<string>("OperatorUsername")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("ProcessName")
                        .HasMaxLength(80);

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<int?>("SessionId");

                    b.Property<bool>("Success");

                    b.Property<string>("TargetUsername")
                        .HasMaxLength(120);

                    b.Property<DateTime?>("UpdatedAtUtc");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SessionManager.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(160);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<DateTime?>("UpdatedAtUtc");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SessionManager.Domain.Entities.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AgentId")
                        .HasMaxLength(120);

                    b.Property<DateTime?>("AgentLastHeartbeatUtc");

                    b.Property<string>("AgentLastIpAddress")
                        .HasMaxLength(80);

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(40);

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDefault");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<DateTime?>("UpdatedAtUtc");

                    b.HasKey("Id");

                    b.HasIndex("Hostname")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("SessionManager.Domain.Entities.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(260);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<DateTime?>("UpdatedAtUtc");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("SessionManager.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<bool>("IsActive");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<DateTime?>("UpdatedAtUtc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SessionManager.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SessionManager.Domain.Entities.AgentCommand", b =>
                {
                    b.HasOne("SessionManager.Domain.Entities.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("SessionManager.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("SessionManager.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionManager.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SessionManager.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SessionManager.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
